### ISSUE TITLE
adding the author function in the libgen scraping 

### ISSUE THREAD

**Issue by tarun4632** [anupammaurya6767/web_scrapper#5]
right now what your code is doing that searching the name that it got by the user and returning the first book it gets back 
what i wanna add is find by the author where the user will search by author and will return all the books that are listed under that author and then make a function where the user will tell which book he or she wants 
can i work on this issue ? @anupammaurya6767

**Comment by tarun4632** [comment]
i want to do this under hacktober fest

**Comment by vibhavp6** [comment]
I have found your Library Genesis (LibGen) scraping project on GitHub, and as a Python enthusiast, I am eager to contribute to your project. Specifically, I would like to propose adding an 'author function' feature. This feature would enable the scraper to retrieve books by a specific author's name, thereby enhancing the flexibility and usefulness of the project.

Events like Hacktoberfest, which actively encourages open-source contributions, are coming up soon (from Oct 1 - 31), and I was hoping to use this feature augmentation as my contribution.

However, in order to proceed, I would appreciate it if you could grant me comment and collaborative permissions on your repository.

Thank you for considering this request. I look forward to the possibility of working on the project and contributing to its advancement.
